// fUNCTION dEFAULT PARAMETER 
function sum (num1=0,num2=0){
    let sum =num1+num2
    console.log(num1,num2,sum)
    return sum ;
}
sum(10)
// default parameter for  string 

function add_name(name1='',name2=''){
    let addName=name1+" "+name2;
    console.log(addName)
    return addName

}
add_name('raj',)
// default parameter for array 

function default_array(value=[]){

}
// default parameter for object 
function default_object(value2={}){

}